name: car_inspection
description: Car on Sale test project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^4.5.1+1
  google_fonts: ^2.1.0
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  build_runner: ^2.1.4
  image_picker: ^0.8.5
  shared_preferences: ^2.0.13

  # Firebase
  firebase_storage: ^10.2.13
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile_placeholder.png
